### ISSUE TITLE
bug: use of ibis-substrait 2.9.3 in tpc-queries fails

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/ibis-substrait#282]
A bizarre protobuf failure occurs when using ibis-substrait 2.9.3 as a dependency of tpc-queries when running in CI [here](https://github.com/ibis-project/ibis/runs/7458966745?check_suite_focus=true).

I'm able to reproduce this, but only when using pip or conda, not when using the nix setup.

What's strange is that the generated code seems to be missing the new `UserDefined` literal type entirely, which is the proximate cause of the problem.

For now, I'm installing 2.9.2 when running tpc-queries CI in ibis in [this PR](https://github.com/ibis-project/ibis/pull/4265).

**Comment by gforsyth** [comment]
this is very odd

**Comment by gforsyth** [comment]
This is extra wacky -- it's picking up on name changes in the `proto` files but is simultaneously failing to use that information:
```
Traceback (most recent call last):
  File "/home/gil/github.com/ibis-project/tpc-queries/./runtpc", line 3, in <module>
    import ibis_tpc
  File "/home/gil/github.com/ibis-project/tpc-queries/ibis_tpc/__init__.py", line 2, in <module>
    from .runners import *
  File "/home/gil/github.com/ibis-project/tpc-queries/ibis_tpc/runners.py", line 18, in <module>
    from .substrait import TPCHBackend
  File "/home/gil/github.com/ibis-project/tpc-queries/ibis_tpc/substrait.py", line 7, in <module>
    from ibis_substrait.compiler.core import SubstraitCompiler
  File "/home/gil/github.com/ibis-project/ibis-substrait/ibis_substrait/compiler/core.py", line 12, in <module>
    from ..proto.substrait import algebra_pb2 as stalg
  File "/home/gil/github.com/ibis-project/ibis-substrait/ibis_substrait/proto/substrait/algebra_pb2.py", line 12, in <module>
    from ..substrait import type_pb2 as substrait_dot_type__pb2
  File "/home/gil/github.com/ibis-project/ibis-substrait/ibis_substrait/proto/substrait/type_pb2.py", line 34, in <module>
    _TYPE_USERUNDEFINED = _TYPE.nested_types_by_name['UserUndefined']
KeyError: 'UserUndefined'
```

**Comment by gforsyth** [comment]
Hmm, and if I comment out `UserDefined` entirely I instead get a `KeyError` on `Parameter`, which is the message defined immediately after `UserDefined`

**Comment by cpcloud** [comment]
Yeah, for some reason the newly added types aren't in the `_TYPE` descriptor. I'm not sure why.

**Comment by gforsyth** [comment]
Also quite puzzling to me (unless I'm missing some weird edge case of the python import system) is that I can import the `type_pb2` module in a REPL without any errors

**Comment by gforsyth** [comment]
DuckDB as of version 0.3.4 was bundling Substrait as a part of their Python library. Substrait is built with protobuf and protobuf has a global descriptor pool by default. So if two libraries (say, duckdb and ibis-substrait) each use a message type with the same name, whichever library is imported first will be the one that defines which message types are available.

The failure on Ibis' CI was because we were pulling in DuckDB 0.3.4, which was preventing the newer version of Substrait included in ibis-substrait from loading into the descriptor pool, which then led to a KeyError when we attempted to look up a message type that should have existed.

Other workarounds were to set $PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION="python" because the Python implementation provides a mutable global descriptor pool, so it's possible to overwrite the available message types.

This shouldn't be as much of a problem as Substrait stabilizes, but even so, it's worth looking into how to namespace the substrait protos so that we are looking up a message type that includes the identifier ibis-substrait in the lookup path and hopefully avoid collisions with other bundled substraits.

xref: ibis-project/ibis#4266
xref: ibis-project/tpc-queries#5
